# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore MVC_app/MVC_app.sln
    - name: Build
      run: dotnet build  MVC_app/MVC_app.sln --no-restore
    - name: Test
      run: dotnet test MVC_app/MVC_app.sln --no-build --verbosity normal

    - name: Build and push Docker image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        context: .
        push: true
        image: dchand2021/demo-app
        registry: docker.io
        tags: dchand2021/my-repo:${{ github.sha }}
        dockerfile: ./Dockerfile
        build-args: |
          ARG_NAME=VALUE
      env:
        DOCKER_USERNAME: dchand2021
        DOCKER_PASSWORD: Welcome@1982



    
        
    
